fix: add rollback

diff --git a/.github/workflows/pipeline.yaml b/.github/workflows/pipeline.yaml
--- a/.github/workflows/pipeline.yaml
+++ b/.github/workflows/pipeline.yaml
@@ -157,15 +157,17 @@ jobs:
                 failures=$(az monitor app-insights query --app ${{ secrets.APPLICATION_INSIGHTS_STAGING_ID }} --analytics-query "exceptions | where timestamp >= ago(1m) | count")
                 echo "::set-output name=failures::$failures"
 
+          - name: Rollback to 0% if Recent Failures Detected
+            if: ${{ steps.check-recent-failures.outputs.failures != '0' }}
+            run: |
+                az login --service-principal -u ${{ secrets.AZURE_SERVICE_PRINCIPAL }} -p ${{ secrets.AZURE_SERVICE_PRINCIPAL_PASSWORD }} --tenant ${{ secrets.AZURE_TENANT_ID }}
+                az webapp traffic-routing set -g ${{ secrets.AZURE_RESOURCE_GROUP }} --name ${{ vars.AZURE_WEBAPP_NAME }} --distribution STAGING=0 --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}
+                exit 1  # Explicitly exit with a failure status code
 
           - name: Update Traffic Routing 100%
             run: |
               az login --service-principal -u ${{ secrets.AZURE_SERVICE_PRINCIPAL }} -p ${{ secrets.AZURE_SERVICE_PRINCIPAL_PASSWORD }} --tenant ${{ secrets.AZURE_TENANT_ID }}
               az webapp traffic-routing set -g ${{ secrets.AZURE_RESOURCE_GROUP }} --name ${{ vars.AZURE_WEBAPP_NAME }}  --distribution STAGING=100 --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}
-
-          - name: Sleep for 30 seconds
-            run: sleep 30s
-            shell: bash
 
           - name: Swap Azure Web App Slots
             run: |
